DROP TABLE IF EXISTS DERROTAMONSTRO, VISUAL, ACESSORIO, ARMADURA, MUNDO, PERSONAGEM, INVENTARIO, MASCOTE, MONSTRO ,CAIXA, EQUIPAMENTO;


CREATE TABLE EQUIPAMENTO(
nomeEquipamento VARCHAR(20) NOT NULL PRIMARY KEY,
statusEquipamento VARCHAR(20) NOT NULL,
nivelRequirido INTEGER NOT NULL
);

CREATE TABLE CAIXA(
idCaixa INTEGER NOT NULL PRIMARY KEY,
raridade VARCHAR(20) NOT NULL,
quantidadeItens INTEGER NOT NULL,
nomeEquipamento VARCHAR(20) NOT NULL,
FOREIGN KEY (nomeEquipamento) REFERENCES EQUIPAMENTO(nomeEquipamento)	
);

CREATE TABLE MONSTRO(
nomeMonstro VARCHAR(20) NOT NULL PRIMARY KEY,
nivel INTEGER NOT NULL,
raca VARCHAR(20),
idCaixa INTEGER NOT NULL,
FOREIGN KEY (idCaixa) REFERENCES CAIXA(idCaixa)
);

CREATE TABLE MASCOTE(
nomeMascote VARCHAR(20) NOT NULL PRIMARY KEY,
raca VARCHAR(20) NOT NULL,
nivelRequirido INTEGER NOT NULL
);

CREATE TABLE INVENTARIO(
idInventario INTEGER NOT NULL PRIMARY KEY,
capacidadeMaxima INTEGER NOT NULL,
quantidadeItens INTEGER NOT NULL,
nomeMascote VARCHAR(20) NOT NULL,
nomeEquipamento VARCHAR(20) NOT NULL,
FOREIGN KEY (nomeMascote) REFERENCES MASCOTE(nomeMascote),
FOREIGN KEY (nomeEquipamento) REFERENCES EQUIPAMENTO(nomeEquipamento)
);

CREATE TABLE PERSONAGEM(
nomePersonagem VARCHAR(20) NOT NULL PRIMARY KEY,
idPersonagem VARCHAR(20) NOT NULL,
nivel INTEGER NOT NULL,
idInventario INTEGER NOT NULL,
nomeMascote VARCHAR(20) NOT NULL,
nomeEquipamento VARCHAR(20) NOT NULL,
FOREIGN KEY (idInventario) REFERENCES INVENTARIO(idInventario),
FOREIGN KEY (nomeMascote) REFERENCES MASCOTE(nomeMascote),
FOREIGN KEY (nomeEquipamento) REFERENCES EQUIPAMENTO(nomeEquipamento)
);

CREATE TABLE MUNDO(
nomeMundo VARCHAR(20) NOT NULL PRIMARY KEY,
idMundo INTEGER NOT NULL,
tipoMundo VARCHAR(20) NOT NULL,
nomeMonstro VARCHAR(20) NOT NULL,
nomePersonagem VARCHAR(20) NOT NULL,
FOREIGN KEY (nomeMonstro) REFERENCES MONSTRO(nomeMonstro),
FOREIGN KEY (nomePersonagem) REFERENCES PERSONAGEM(nomePersonagem)
);

CREATE TABLE ARMADURA(
nomeEquipamento VARCHAR(20) NOT NULL PRIMARY KEY,
descricao VARCHAR(20) NOT NULL,
tipo VARCHAR(20) NOT NULL,
slot INTEGER NOT NULL,
FOREIGN KEY (nomeEquipamento) REFERENCES EQUIPAMENTO(nomeEquipamento) ON DELETE CASCADE
);

CREATE TABLE ACESSORIO(
nomeEquipamento VARCHAR(20) NOT NULL PRIMARY KEY,
descricao VARCHAR(20) NOT NULL,
slot INTEGER NOT NULL,
habilidade VARCHAR(20) NOT NULL,
FOREIGN KEY (nomeEquipamento) REFERENCES EQUIPAMENTO(nomeEquipamento) ON DELETE CASCADE
);

CREATE TABLE VISUAL(
nomeEquipamento VARCHAR(20) NOT NULL PRIMARY KEY,
raridade VARCHAR(20) NOT NULL,
descricao VARCHAR(20) NOT NULL,
cor VARCHAR(20) NOT NULL,
FOREIGN KEY (nomeEquipamento) REFERENCES EQUIPAMENTO(nomeEquipamento) ON DELETE CASCADE
);

CREATE TABLE DERROTAMONSTRO(
nomeMonstro VARCHAR(20) NOT NULL,
nomePersonagem VARCHAR(20) NOT NULL,
PRIMARY KEY(nomeMonstro, nomePersonagem),
FOREIGN KEY (nomeMonstro) REFERENCES MONSTRO(nomeMonstro),
FOREIGN KEY (nomePersonagem) REFERENCES PERSONAGEM(nomePersonagem)
);

